// Exportaciones centralizadas de componentes base
export { default as Icono } from './Icono'
export type { NombreIcono } from './Icono'
export { iconoPorReaccion } from './Icono'
export { default as Texto } from './Texto'
export { default as Boton } from './Boton'
export { default as Entrada } from './Entrada'
export { default as Tarjeta } from './Tarjeta'
export { default as Cargador } from './Cargador'
export { default as EsqueletoTarjeta } from './EsqueletoTarjeta'
export { default as EstadoVacio } from './EstadoVacio'
export { default as Divisor } from './Divisor'
export { default as Insignia } from './Insignia'
export { default as InsigniaIA } from './InsigniaIA'
export { default as TarjetaPublicacion } from './TarjetaPublicacion'
export { default as BannerNuevasPublicaciones } from './BannerNuevasPublicaciones'
export { default as CargadorFeed } from './CargadorFeed'
export { default as IndicadorConexion } from './IndicadorConexion'
export { default as FormularioComentario } from './FormularioComentario'
export { default as TarjetaComentario } from './TarjetaComentario'
export { default as ListaComentarios } from './ListaComentarios'
export { default as TarjetaNotificacion } from './TarjetaNotificacion'
export { default as BadgeNotificaciones } from './BadgeNotificaciones'
export { default as CabeceraPerfil } from './CabeceraPerfil'
export { default as EstadisticasPerfil } from './EstadisticasPerfil'
export { default as AvatarPerfil } from './AvatarPerfil'
export { default as EnlacesRedesSociales } from './EnlacesRedesSociales'
export { default as FormularioEditarPerfil } from './FormularioEditarPerfil'
export { default as TarjetaHistorial } from './TarjetaHistorial'
export { default as HistorialComentarios } from './HistorialComentarios'
export { default as ModalDenuncia } from './ModalDenuncia'
export { default as BarraBusqueda } from './BarraBusqueda'
export { default as BotonesReaccion } from './BotonesReaccion'
